name: Create branch from issue

on:
  issues:
  create:
  
jobs:
  create_branch:
    runs-on: [ubuntu-latest]
    steps:
      - name: Branch main repo
        env:
          BRANCH: ${{github.ref}}
          USER: ${{github.actor}}
        run: git branch $USER
