name: Test-Code

on:
  pull_request:
     branches: master 

jobs:
  test:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
    - name: Run python unit test
      run: python text_exec.py
