name: Test-Code

on:
  pull_request:
     branches: master
     paths: 
       - '**.py'

jobs:
  test:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
    - name: Run python unit test
      run: python test.py
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@2c8e667a3386187418587517e5bfe33470d19b5b"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
