name: Test-Code

on:
  pull_request:
     branches: master 

jobs:
  test:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
    #- uses: rlespinasse/github-slug-action@1.0.1
    - name: Run python unit test
      run: python /tests/test.py
    #  run: python test_exec.py ${{ env.GITHUB_HEAD_REF_SLUG }
